### ISSUE TITLE
MaximumAndMinimum returns (min, max) instead of (max,min) as suggested in the document or method name

### ISSUE THREAD

**Issue by qpxu007** [DIPlib/diplib#184]
import numpy as np
import diplib as dip

image = dip.Image(np.array([[1,1,1], [2,-2,2], [3,3,3]]))

print(dip.MaximumAndMinimum(image))

(-2.0, 3.0)

**Comment by crisluengo** [comment]
This is a good point.

I'm unsure whether to fix this or not. The [documentation](https://github.com/DIPlib/diplib/blob/fde5d12811730d40897244d90daa8059e7b7ff06/pydip/src/statistics.cpp#L39) gives the right information about the output, and changing this order will break existing code that uses this function.

There are some functions that return a struct in C++, where I was too lazy making the bindings and just returned a tuple with the values instead of binding the actual struct. I regret that now.

Maybe we can turn these into `namedtuple`? Pybind11 doesn't support `namedtuple`, so it'd be a bit of work, but then we'd have names for these output values without breaking existing code.

I'm happy to hear any suggestions on how to improve this output!

**Comment by crisluengo** [comment]
Functions that return a tuple in Python instead of the original struct:
 - `dip::MandersColocalizationCoefficients` and `dip::CostesColocalizationCoefficients`
 - `dip::MaximumAndMinimum` (both the one applied to a measurement feature and applied to an image)
 - `dip::BoundingBox` (both applied to a polygon and a chain code)
 - `dip::ChainCode::start`

This is just 4 types that need a binding but don't have one. We could overload the `__getitem__` method to emulate the tuple behavior, so that existing code doesn't break.

**Comment by qpxu007** [comment]
To clarify, I was referring to this documentation:

https://diplib.org/diplib-docs/math_statistics.html#dip-MaximumAndMinimum-Image-CL-Image-CL

"Finds the largest and smallest value in the image, within an optional mask.", adding a note on what is returned certainly help.

One could use max(returned tuple), min(returned_tuple) in their python calls to circumvent this issue

**Comment by crisluengo** [comment]
This is addressed in 008c18600010ea13ab63c8abc3fdf4b03e33a57e.

That commit also uses `namedtuple` for many other output-only types, simplifying and reducing the code that creates the Python bindings.

**Comment by crisluengo** [comment]
> To clarify, I was referring to this documentation:
> 
> https://diplib.org/diplib-docs/math_statistics.html#dip-MaximumAndMinimum-Image-CL-Image-CL
> 
> "Finds the largest and smallest value in the image, within an optional mask.", adding a note on what is returned certainly helps.

But the C++ output type doesn't have an order, the two values there can only be accessed using names.

I think that adding these names to the output in Python clarifies what you get, and solves this issue.
