### ISSUE TITLE
Compile fail on ARM (BeagleBone AI)

### ISSUE THREAD

**Issue by Vladimirek** [DIPlib/diplib#51]
Hello, 

I would like to point on one issue.

I try this nice lib on the new BeagleBone AI (ARM Cortex-A15).
I found a issue when compile with gcc ( Version: (Debian 8.3.0-6) 8.3.0). I compile it directly on the device not a cross.

Problem was lines 128/129, gcc reporting struct redefine. [here](https://github.com/DIPlib/diplib/blob/4c2db121f8993903288d1a23a64568a433a09e76/include/diplib/library/types.h#L128)

After apply attached "Ugly Fix", compile go without problem and the library is going well.
I play with a python little bit and did not found any issue.

[patch_diplib_arm.txt](https://github.com/DIPlib/diplib/files/4257664/patch_diplib_arm.txt)

I am not strong in C++ so please review and provide "official" patch. 

This is really nice lib. Thanks.  

-vladimirek-

**Comment by crisluengo** [comment]
Many thanks for the report! You are the first person I know of to attempt to compile the library on a 32-bit architecture. I'm pleasantly surprised that you only found one problem! :)

Your fix would not provide the right definitions on a 64-bit architecture.

I will look for an alternative solution. It is clear that on 32-bit architectures we only need one of those two groups of declarations, since they are identical there. On 64-bit architectures they are different, and both sets are needed.

**Comment by crisluengo** [comment]
@Vladimirek Could you please try this for me?

1. Undo the change that you made
2. add `#include <climits>` somewhere at the top of the file with the other includes.

It seems that `UINT_MAX` is defined in that header but it's not directly included by this file.

**Comment by Vladimirek** [comment]
Well done Cris - fast response ! 

I try to recompile against master and it was without errors. 
BTW: It took 45min with -j2, and with fine fit to <1G RAM and not use swap.

Again, great job and thanks for the lib.

Used patch:
---------------
diff --git a/include/diplib/library/types.h b/include/diplib/library/types.h
index 2af54a0a..d202dcce 100644
--- a/include/diplib/library/types.h
+++ b/include/diplib/library/types.h
@@ -35,6 +35,7 @@
 #include <string>
 #include <set>
 #include <cctype>
+#include <climits>
 
 #include "diplib/library/dimension_array.h"

**Comment by crisluengo** [comment]
Many thanks for trying that out!
