### ISSUE TITLE
Installation problem: Invalid MEX_file  libMatlabEngine.so: cannot open shared object file

### ISSUE THREAD

**Issue by thorstenwagner** [DIPlib/diplib#88]
Hi,

I followed the installation instructions for building DIPimage (3.1.0) on Linux. The installation went fine, but when I try to start `dipimage` in matlab I get the following error:

```
Warning: Call to DIPMENUS failed:

Invalid MEX-file '/opt/user_software/share/DIPimage/measure.mexa64': libMatlabEngine.so: cannot open shared object file: No such file or directory
```

I'm using MatLab R2021b. Does someone knows what is going on?

Best,
Thorsten

**Comment by crisluengo** [comment]
In the DIPlib sources there is a file `tools/FindMatlab.cmake`, which is used by CMake to figure out how to build MEX-files. This file contains, on lines 1009-1011 the following:
```none
  if(Matlab_HAS_CPP_API)
    target_link_libraries(${${prefix}_NAME} ${Matlab_ENGINE_LIBRARY} ${Matlab_DATAARRAY_LIBRARY})
  endif()
```
Please try deleting (or commenting out) these lines, then do
```bash
touch include/dip_matlab_interface.h
```
to force recompilation of all MEX-files, and finally, run `make install` again. The `make` command should now re-compile the MEX-files. And these new MEX-files should no longer attempt to link to `libMatlabEngine.so` nor `libMatlabDataArray.so`. From what I can tell from the docs, `libMatlabDataArray.so` is only used by MEX-files using the new C++ API (which we don't use here), and `libMatlabEngine.so` is not at all used by MEX-files, so it should never have been linked in.

I'm pretty sure this will fix your issue, but I can't test it myself because I don't have a MATLAB on Linux, and I also don't have the latest version of MATLAB installed (still at R2018b! -- I should really upgrade at some point).

Please let us know if this works or not!

**Comment by thorstenwagner** [comment]
OK, thanks a lot for all the information. I think we cab close the issue :-)
