### ISSUE TITLE
Building with Ninja + Mingw64 on Windows

### ISSUE THREAD

**Issue by hussainkadori** [DIPlib/diplib#90]
Hi,
I want to use Ninja + Mingw64 on windows to build the library but I have this error

```
C:/Users/hk/diplib/src/library/information.cpp:25:37: error: external linkage required for symbol 'dip::libraryInformation' because of 'dllexport' attribute
 DIP_EXPORT LibraryInformation const libraryInformation{
                                     ^~~~~~~~~~~~~~~~~~
```
This is the Output of cmake

```
~~Configuring Zlib~~~
~~~
~~~Configuring libics~~~
~~~Configuring LibTIFF~~~
LibTIFF uses win32 IO: TRUE
LibTIFF has JPEG 8/12 bit dual mode: FALSE
~~~
Could NOT find FFTW3 (missing: FFTW3_INCLUDE_DIR FFTW3_LIBRARY_FFTW3F FFTW3_LIBRARY_FFTW3) 
Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Development) (Required is at least version "1.7")
Could NOT find FreeGLUT (missing: FREEGLUT_LIBRARY FREEGLUT_INCLUDE_DIR) 
FreeGLUT not found
Found GLFW: C:/Users/hk/Desktop/lib-mingw-w64/libglfw3.a  
GLFW found: C:/Users/hk/Desktop/lib-mingw-w64/libglfw3.a -- C:/Users/hk/Desktop/lib-vc2019/include
Looking for pthread.h
Looking for pthread.h - found
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
Found Threads: TRUE  

--------------------------------------
   DIPlib CONFIGURATION REPORT

 * PROJECT_VERSION: 3.1.0
 * DIP_COPYRIGHT_YEAR: 2021
 * C++ compiler: GNU 8.1.0
 * C++ compiler flags:  -Wall -Wextra -Wconversion -Wsign-conversion -pedantic -Wno-unknown-pragmas -Wno-attributes -O3 -DNDEBUG
 * Build type: Release
 * Building shared library
 * Library installed to: C:/Users/hk/diplib_windows/bin
 * Binaries installed to: C:/Users/hk/diplib_windows/bin
 * Import library installed to: C:/Users/hk/diplib_windows/lib
 * Header files installed to: C:/Users/hk/diplib_windows/include
 * dox++ program not configured, no documentation can be generated
 * Using OpenMP for multithreading
 * Stack trace recording enabled
 * Asserts disabled
 * Unicode support enabled
 * Using 128-bit PRNG
 * ICS file IO enabled, with zlib
 * TIFF file IO enabled, with zlib, with JPEG
 * JPEG file IO enabled
 * Using built-in FFT
 * Unit test code excluded
 * DIPviewer module added to 'all' with window managers: GLFW
 * DIPviewer Java bindings not configured
 * DIPJavaio module not configured
 * PyDIP module not configured
 * DIPimage toolbox not configured

--------------------------------------

Configuring done
Generating done
```

**Comment by hussainkadori** [comment]
> Interesting! This issue hasn't come up with MSVC compiler on Windows, nor with GCC and Clang compilers on Linux and macOS. But it seems indeed that a `extern` keyword is missing in that line.
> 
> So, on line 25 of the file `C:/Users/hk/diplib/src/library/information.cpp`, which now reads:
> 
> ```c++
> DIP_EXPORT LibraryInformation const libraryInformation{
> ```
> 
> should instead read
> 
> ```c++
> DIP_EXPORT extern LibraryInformation const libraryInformation{
> ```
> 
> Could you please make this change and let us know if the issue is resolved?
> 
> Thanks!

Thanks It resolved the issue here but at the end there are two errors in display.h and image.h

```
In file included from C:/Users/hk/diplib/include/diplib.h:35,
                 from C:/Users/hk/diplib/include/diplib/viewer/viewer.h:27,
                 from C:\Users\hk\diplib\viewer\src\colormap.cpp:20:
C:/Users/hk/diplib/include/diplib/library/image.h:1657:25: error: function 'dip::Image& dip::Image::Squeeze()' definition is marked dllimport
       DIP_EXPORT Image& Squeeze() {
                         ^~~~~~~
In file included from C:/Users/hk/diplib/include/diplib/viewer/viewer.h:29,
                 from C:\Users\hk\diplib\viewer\src\colormap.cpp:20:
C:/Users/hk/diplib/include/diplib/display.h:194:31: error: function 'dip::Image::Pixel dip::ImageDisplay::Pixel(dip::uint, dip::uint)' definition is marked dllimport
       DIP_EXPORT Image::Pixel Pixel( dip::uint x, dip::uint y = 0 ) {

```

**Comment by felixf4xu** [comment]
> ```c++
> DIP_EXPORT extern LibraryInformation const libraryInformation{
> ```

I don't quite understand it from c++ syntax point of view.

If `extern` is used both in the .h and .cpp file, the symbol of `libraryInformation` will not be in the .dll, then `dllexport` make no sense. 

Not sure if my understanding of the c++ `extern` and `dllexport` is correct or not.

**Comment by crisluengo** [comment]
@felixf4xu In the .cpp file, `extern` shouldn't be needed, but the Mingw64 compiler error indicated that it was expecting that to be there. Since it didn't bother the other compilers, I figured it's OK to add it.

`extern` in the *declaration* of a variable indicates that the variable is defined somewhere else. In the *definition* of a variable it apparently doesn't do anything. The symbol **is** defined in the library.

`dllexport` is a Windows thing, I don't really have a good understanding of how it's used. It needs to be given at least once for each symbol. In DIPlib we typically put it where the symbol is declared, so that it can become `dllimport` when people use the same headers in their programs. But if it's given again in the source file, it shouldn't matter at all.

**Comment by crisluengo** [comment]
Though maybe that's it. The original MinGW error message was "error: external linkage required for symbol 'dip::libraryInformation' because of 'dllexport' attribute". We had the unnecessary `dllexport` there (unnecessary because it was already given in the declaration), and MinGW wanted to always see `export` next to `dllexport`, no matter if the symbol had earlier already been declared as `dllexport` or not.

So, hopefully, removing both will also satisfy MinGW?
