### ISSUE TITLE
Convert datatype of MATLAB array

### ISSUE THREAD

**Issue by HHHit** [DIPlib/diplib#94]
**Component**
DIPlib / DIPimage 

**Describe the bug**
After converting the MATLAB array into DIP::image, how to convert the data type? Using dip::Copy reports the error "bad allocation" in MATLAB.

**To Reproduce**
dipMatlabTest.cpp

```
#include <dip_matlab_interface.h>
#include <diplib/mapping.h> 
#include <diplib/math.h> 
#include <diplib/distance.h>
void mexFunction(int /*nlhs*/, mxArray* plhs[], int nrhs, const mxArray* prhs[]) {
    try {
        // The first input argument is an image
        dip::Image in = dml::GetImage(prhs[0]);
        dip::Image inBin = in.Similar(dip::DT_BIN);
        inBin = dip::Copy(in);    
} DML_CATCH
}
```

matlab test.m

```
xx = [0,0,0,0,0,0;0,0,0,1,0,0;0,0,1,1,1,0;0,0,1,1,0,0;0,0,0,0,0,0];
dipMatlabTest(xx);
```
**System information:**
 - Windows 10
 - MATLAB 2021

'in' is with 'float' datatype, and I am hoping to convert it to binary using functions of diplib.

**Comment by crisluengo** [comment]
I think you want to use [`dip::Convert`](https://diplib.org/diplib-docs/dip-Image.html#dip-Convert-dip-Image-CL-dip-Image-L-dip-DataType-):
```cpp
dip::Image inBin = dip::Convert(in, dip::DT_BIN);
```
But you could also use your approach, just change it as follows:
```cpp
dip::Image inBin = in.Similar(dip::DT_BIN);
inBin.Copy(in);
```

But note that converting to binary this way is only useful if `in` is already binary, but just has the wrong data type. Any zero value will become “false”, any other value will become “true”.

Otherwise, look at the [Segmentation module](https://diplib.org/diplib-docs/segmentation.html), or just use comparison operators:
```cpp
dip::Image inBin = in > 50;
```

**Comment by HHHit** [comment]
Thanks! I think I can use the comparison operators. Because in my case, 'in' is not binary.

**Comment by crisluengo** [comment]
Also, note that it is dangerous to access `prhs[0]` without checking that it exists. If you accidentally call your MEX-file without an input argument, you could crash MATLAB. 

There’s a macro `DML_MIN_ARGS(n)` that will throw an exception if there are fewer than `n` inputs.

**Comment by HHHit** [comment]
Thanks a lot for the advice. I saw there are two macros in the example you gave to examine the number of input and outputs, very helpful!
