### ISSUE TITLE
MATLAB interface "error reading characters of string "

### ISSUE THREAD

**Issue by HHHit** [DIPlib/diplib#95]
**Component**
DIPlib / DIPimage

**Describe the bug**
While running the code including the matlab interface.
`dip::EuclideanDistanceTransform(in, dist0, "background", "separable");`
I input two strings into the function "EuclideanDistanceTransform", but it reports an error saying the strings were not read well (access violation).
For one parameter (which should read in "background")
 
![image](https://user-images.githubusercontent.com/16516097/142562559-a4e2359b-a01e-4f2a-afd0-0eeebd7baf47.png)
for the other parameter (which should read in "separable")
![image](https://user-images.githubusercontent.com/16516097/142562605-f9136fec-2640-4b81-b1e7-59bb03ac8554.png)
somehow, garbled strings are read into memory.
The weird thing is when I run a very similar code using diplib directly, it works well. I am really confused why this happened. Hope someone can help. 

**To Reproduce**

```
#include <dip_matlab_interface.h>
#include <diplib/mapping.h> // for dip::ContrastStretch
#include <diplib/math.h> // for dip::Floor
#include "diplib/file_io.h"
#include "diplib/linear.h"
#include "diplib/generation.h"
#include "diplib/mapping.h"
#include "diplib/statistics.h"
#include "diplib/distance.h"
#include "diplib/binary.h"
#include <iostream>
#include <string>
using namespace std;
void mexFunction(int /*nlhs*/, mxArray* plhs[], int nrhs, const mxArray* prhs[]) {
    try {

        DML_MIN_ARGS(1); // This ensures there is at least one input argument
        DML_MAX_ARGS(2); // This ensures there are not more than two input arguments

        // The first input argument is an image
        dip::Image in = dml::GetImage(prhs[0]);
        dip::Image dist0;
        dip::EuclideanDistanceTransform(in, dist0, string("background"), string("separable"));
        for (size_t i = 0; i < dist0.Size(0); i++)
        {
            for (size_t j = 0; j < dist0.Size(1); j++)
            {
                mexPrintf("%f\t", dist0.At(i, j).As<double>());
            }
            mexPrintf("\n");
        }
    } DML_CATCH
}
```

**System information:**
 -Windows 10, Matlab 2021, dipmex compile using visual studio 2019

**Comment by crisluengo** [comment]
I cannot reproduce the issue on macOS, the code works as intended. This looks to be another issue in MSVC.

Please try without the explicit cast to `string`:
```cpp
dip::EuclideanDistanceTransform(in, dist0, "background", "separable");
```
That is how the DIPimage MEX-files are all written, so I expect that to work if the DIPimage MEX-files work on your system.

If that doesn't solve the issue, then there must be a problem with compiler settings when building the MEX-file. I assume you use the `dipmex` function?

**Comment by crisluengo** [comment]
Did you configure your `max` command to use the same version of MSVC that you used to build DIPlib?
Run `mex -setup C++`, then select the right compiler.

**Comment by HHHit** [comment]
Yes, I used dipmex function and I used the same compiler (visual studio 2019) to build DIPlib and for mex.

**Comment by crisluengo** [comment]
Type `edit dipmex`, and you'll see exactly what the `dipmex` function does. It just calls `mex` with a specific set of command line arguments. Feel free to replicate what it does and/or build the MEX-file in a different way.

If I had access to a Windows machine, I might be able to try to reproduce this issue and look for the cause, but all I can do is stare at your screen shots and scratch my head. It makes no sense to me, I don't see how this is possible.

One thing you could do is add your MEX-file sources to the `dipimage/` directory in the DIPlib source tree, and build it as part of the library. Not an ideal situation in the long run, but it might help you discover what the issue is. Again, I don't know how to do this with MSVC, but try to look at the actual build commands issued when your MEX-file is built this way, see if there are any differences to command-line options compared to `dipmex -v ...`.

**Comment by HHHit** [comment]
After uninstalling the visual studio completely and reinstalling it, I somehow solved the issue. Thanks for pointing out the issue is related to MSVC.
